#!/usr/bin/env python3
"""Independent reference for Reliks protocol primitives (see PROTOCOL.md). Written from the spec text,
not from web/reliks-chain.js. Regenerates sdk/protocol-vectors.json deterministically."""
import hashlib, json, os, struct

def b2(data, key=b''): return hashlib.blake2b(data, digest_size=32, key=key).digest()
def le16(n): return struct.pack('<H', n)
def le32(n): return struct.pack('<I', n)
def le64(n): return struct.pack('<Q', n)
T = lambda s: hashlib.sha256(s.encode()).hexdigest()

def serial(txid, index):
    h = b2(b'ReliksSerialV10' + bytes.fromhex(txid) + le32(index))
    return str(int.from_bytes(h[:7], 'little') + (h[7] % 128) * (1 << 56))
def genesis_lineage(txid, index): return b2(b'ReliksGenesisV2' + bytes.fromhex(txid) + le32(index)).hex()
def advance_lineage(prev, owner): return b2(b'ReliksLineageV2' + bytes.fromhex(prev) + bytes.fromhex(owner)).hex()
def covenant_id(txid, index, outs):
    p = [bytes.fromhex(txid), le32(index), le64(len(outs))]
    for o in outs:
        sc = bytes.fromhex(o['script'])
        p.append(le32(o['idx']) + le64(o['value']) + le16(0) + le64(len(sc)) + sc)
    return b2(b''.join(p), b'CovenantID').hex()

ED13 = [('ownerIdentifier', 32), ('identifierType', 1), ('price', 8), ('artist', 32), ('royalty_bips', 8), ('program_hash', 32), ('factory_covid', 32), ('serial', 8), ('lineage', 32), ('sales', 8)]
FC = [('program_hash', 32), ('artist', 32), ('price', 8), ('royalty_bips', 8), ('mints_left', 8), ('engine_lang', 8), ('render_hash', 32)]
def enc(tbl, s):
    out = b''
    for name, w in tbl:
        v = s[name]
        if w == 8:
            x = int(v)
            if not 0 <= x < (1 << 63): raise ValueError('int out of range: ' + name)
            b = struct.pack('<Q', x)
        elif w == 1: b = bytes([int(v) & 255])
        else:
            b = bytes.fromhex(v)
            if len(b) != w: raise ValueError('bad length: ' + name)
        out += bytes([len(b)]) + b
    return out

def edition(**kw):
    s = dict(ownerIdentifier=T('own'), identifierType='0', price='100000000', artist=T('art'), royalty_bips='500', program_hash=T('prog'),
             factory_covid=T('lane'), serial=serial(T('lane-a'), 0), lineage=genesis_lineage(T('lane-a'), 0), sales='0')
    s.update({k: str(v) for k, v in kw.items()}); return s
def factory(**kw):
    s = dict(program_hash=T('prog'), artist=T('art'), price='100000000', royalty_bips='500', mints_left='5', engine_lang='2', render_hash=T('render'))
    s.update({k: str(v) for k, v in kw.items()}); return s

def build():
    V = {'_note': 'generated by sdk/ref_protocol.py; do not edit'}
    V['serial'] = [{'label': 'idx %d' % i, 'txid': T('lane-%d' % k), 'index': i, 'serial': serial(T('lane-%d' % k), i)}
                   for k, i in enumerate([0, 1, 2, 255, 65536, 4294967295])]
    V['lineage'] = []
    for c in range(2):
        tx, ix = T('mint-%d' % c), c; cur = genesis_lineage(tx, ix); owners = [T('owner-%d-%d' % (c, i)) for i in range(4)]; chain = []
        for o in owners: cur = advance_lineage(cur, o); chain.append(cur)
        V['lineage'].append({'txid': tx, 'index': ix, 'genesis': genesis_lineage(tx, ix), 'owners': owners, 'chain': chain})
    spk = lambda n: 'aa20' + T('spk' + n) + '87'
    outs = [[{'idx': 1, 'value': 100000000, 'script': spk('a')}],
            [{'idx': 0, 'value': 1, 'script': spk('b')}, {'idx': 1, 'value': 100000000, 'script': spk('c')}],
            [{'idx': 1, 'value': 2 ** 40 + 5, 'script': spk('d')}, {'idx': 2, 'value': 7, 'script': '20' + T('pk') + 'ac'}, {'idx': 5, 'value': 3, 'script': spk('e')}]]
    V['covenant_id'] = [{'txid': T('fund-%d' % i), 'index': i, 'outs': o, 'id': covenant_id(T('fund-%d' % i), i, o)} for i, o in enumerate(outs)]
    eds = [edition(), edition(price=0), edition(price=2 ** 62), edition(sales=255), edition(sales=2 ** 40, identifierType=1), edition(royalty_bips=10000, serial=2 ** 63 - 1)]
    V['edition_state'] = [{'state': s, 'hex': enc(ED13, s).hex()} for s in eds]
    fcs = [factory(), factory(mints_left=0, price=0), factory(engine_lang=1, mints_left=2 ** 62)]
    V['factory_state'] = [{'state': s, 'hex': enc(FC, s).hex()} for s in fcs]
    bad_ed = [edition(price=2 ** 63), edition(sales=-1), edition(ownerIdentifier=T('own')[:62])]
    nolin = edition(); del nolin['lineage']
    bad_fc = [factory(mints_left=2 ** 63)]
    V['rejects'] = [{'kind': 'edition', 'state': s} for s in bad_ed + [nolin]] + [{'kind': 'factory', 'state': s} for s in bad_fc]
    for r in V['rejects']:
        try: enc(ED13 if r['kind'] == 'edition' else FC, r['state'])
        except (ValueError, KeyError): continue
        raise SystemExit('reference accepted an invalid state')
    assert len(enc(ED13, eds[0])) == 203 and len(enc(FC, fcs[0])) == 135
    return V

if __name__ == '__main__':
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'protocol-vectors.json')
    with open(p, 'w') as f: json.dump(build(), f, indent=1, sort_keys=True); f.write('\n')
    print('wrote', p)
