'use strict';
const fs = require('fs');
const ABI = 'v13/out/factory-vm-v13.json', EAB = 'data/edition-abi-v13.json';
if (!fs.existsSync(ABI) || !fs.existsSync(EAB)) { console.log('SKIP no factory ABI on this machine'); process.exit(0); }
const CH = require('../web/reliks-chain.js'), T = require('./templates.js'), L = require('./lane.js');
CH.init(T.templatesFor({ factoryAbi: ABI, editionAbi: EAB }));
let bad = 0;
const t = (n, ok, d) => { if (!ok) bad = 1; console.log((ok ? 'PASS ' : 'FAIL ') + n + (ok ? '' : ' | ' + d)); };
const H = (c) => c.repeat(64), LANE = H('9');
const mk = (m) => ({ program_hash: H('1'), artist: H('2'), price: 100000000n, royalty_bips: 500n, mints_left: m, engine_lang: 2n, render_hash: H('3') });
const S0 = mk(5n), S1 = mk(4n);
const redeemHex = (s) => Buffer.from(CH.factoryRedeem(s)).toString('hex'), spk = (s) => CH.p2shSpk(CH.factoryRedeem(s));
const prevOut = (s, o) => Object.assign({ outpoint: H('a') + ':0', live: false, spent_txid: H('b'), revealed_hex: redeemHex(s), script_hex: spk(s), value: 100000000 }, o || {});
const liveOut = (s, o) => Object.assign({ outpoint: H('b') + ':0', live: true, value: 150000000, script_hex: spk(s) }, o || {});
const rec = (utxos, o) => Object.assign({ genesis_txid: H('a'), events: [{ kind: 'genesis', txid: H('a') }, { kind: 'transition', txid: H('b') }], utxos }, o || {});
const run = (r, o) => L.resolveLaneKascov(Object.assign({ chain: CH, io: { covenant: async () => r }, laneCovenantId: LANE, tipAgeSec: 5 }, o || {}));
const C = async (name, r, status, o, fn) => { const x = await run(r, o); t(name + ' -> ' + status, x.status === status && x.ok === (status === 'resolved') && (!fn || fn(x)), x.status + ' ' + JSON.stringify(x.checks.filter((c) => !c.ok))); };
const G = { genesis_txid: H('a'), events: [{ kind: 'genesis', txid: H('a') }] };
const GL = (s) => [{ outpoint: H('a') + ':0', live: true, value: 100000000, script_hex: spk(s) }];
const SER = { program_hash: H('1'), artist: H('2'), price: 100000000, royalty_bips: 500, mints_left: 5, engine_lang: 2, render_hash: H('3') };
(async () => {
  await C('previous output gives the state', rec([prevOut(S0), liveOut(S1)]), 'resolved', null, (x) => x.state.mints_left === 4n && x.value === 150000000n && x.outpoint.txId === H('b') && x.outpoint.index === 0 && x.source === 'kascov-previous-output' && x.spk === spk(S1) && x.soldOut === false && x.covenantId === LANE);
  await C('unrelated spent outputs are ignored', rec([prevOut(S0, { outpoint: H('7') + ':0', spent_txid: H('8') }), prevOut(S0), liveOut(S1)]), 'resolved');
  await C('genesis lane with the series state', rec(GL(S0), G), 'resolved', { series: SER }, (x) => x.state.mints_left === 5n && x.source === 'series-genesis');
  await C('genesis lane without the series state', rec(GL(S0), G), 'needs_genesis_state');
  await C('genesis lane, series differs', rec(GL(S0), G), 'script_mismatch', { series: Object.assign({}, SER, { price: 200000000 }) });
  await C('genesis lane, unusable series', rec(GL(S0), G), 'needs_genesis_state', { series: { program_hash: H('1') } });
  await C('two live outputs', rec([prevOut(S0), liveOut(S1), liveOut(S1, { outpoint: H('c') + ':0' })]), 'forked');
  await C('no live output', rec([prevOut(S0)]), 'no_live_output');
  await C('history with a fork event', rec([prevOut(S0), liveOut(S1)], { events: [{ kind: 'genesis', txid: H('a') }, { kind: 'fork', txid: H('b') }] }), 'complex_history');
  await C('previous output without a revealed script', rec([prevOut(S0, { revealed_hex: undefined }), liveOut(S1)]), 'previous_state_unavailable');
  await C('previous output spent by another transaction', rec([prevOut(S0, { spent_txid: H('7') }), liveOut(S1)]), 'previous_state_unavailable');
  await C('previous output undecodable', rec([prevOut(S0, { revealed_hex: '00' }), liveOut(S1)]), 'previous_state_unreadable');
  await C('previous state had no mints left', rec([prevOut(mk(0n)), liveOut(mk(0n))]), 'previous_state_unreadable');
  await C('last mint leaves a sold-out lane', rec([prevOut(mk(1n)), liveOut(mk(0n))]), 'resolved', null, (x) => x.soldOut === true && x.state.mints_left === 0n);
  await C('live script does not match the derived state', rec([prevOut(S0), liveOut(S0)]), 'script_mismatch');
  await C('live script of a different series', rec([prevOut(S0), liveOut(Object.assign({}, S1, { artist: H('8') }))]), 'script_mismatch');
  const st = await run(rec([prevOut(S0), liveOut(S1)]), { tipAgeSec: 99999 });
  t('stale index -> index_stale, observed resolved, no state exposed', st.status === 'index_stale' && st.observed === 'resolved' && st.state === undefined && st.ok === false, st.status);
  await C('tip age missing', rec([prevOut(S0), liveOut(S1)]), 'index_stale', { tipAgeSec: undefined });
  await C('boundary 600 s', rec([prevOut(S0), liveOut(S1)]), 'resolved', { tipAgeSec: 600 });
  await C('boundary 601 s', rec([prevOut(S0), liveOut(S1)]), 'index_stale', { tipAgeSec: 601 });
  await C('stale and mismatched reports the mismatch', rec([prevOut(S0), liveOut(S0)]), 'script_mismatch', { tipAgeSec: 99999 });
  await C('invalid lane id', rec([]), 'invalid_input', { laneCovenantId: 'zz' });
  await C('null record', null, 'no_live_output');
  const un = await L.resolveLaneKascov({ chain: CH, io: { covenant: async () => { throw new Error('kascov 502'); } }, laneCovenantId: LANE, tipAgeSec: 5 });
  t('kascov throws -> unreachable', un.status === 'unreachable', un.status);
  let th = false; try { await L.resolveLaneKascov({ chain: CH, laneCovenantId: LANE }); } catch (e) { th = true; }
  t('missing io throws', th);
  console.log(bad ? 'LANE TESTS FAILED' : 'LANE TESTS OK'); process.exit(bad);
})();
