'use strict';
const { createNodeLookup } = require('./node-lookup.js'), { submitSafe } = require('./submit.js');
let bad = 0;
const t = (name, ok, d) => { if (!ok) bad = 1; console.log((ok ? 'PASS ' : 'FAIL ') + name + (ok ? '' : ' | ' + d)); };
const A = 'kaspatest:qqtest', U = ['wss://n1', 'wss://n2'];
const IN = { transactionId: 'ab'.repeat(32), index: 1 }, SIG = '41' + 'cd'.repeat(64) + '01';
const TX = { inputs: [{ previousOutpoint: IN, signatureScript: SIG }, { previousOutpoint: { transactionId: 'ee'.repeat(32), index: 0 }, signatureScript: '00' }] };
const utxos = (list) => JSON.stringify({ id: 1, method: 'getUtxosByAddresses', params: { entries: list.map(([tx, i]) => ({ address: A, outpoint: { transactionId: tx, index: i }, utxoEntry: { amount: '1' } })) } });
const mem = (s, r) => JSON.stringify({ id: 1, method: 'getMempoolEntriesByAddresses', params: { entries: [{ address: A, receiving: r || [], sending: s || [] }] } });
const node = (u, m) => ({ getUtxosByAddresses: u, getMempoolEntriesByAddresses: m });
const mk = (cfg) => createNodeLookup({ urls: U, address: A, call: async (url, method) => { const c = cfg[url]; if (c instanceof Error) throw c; return c[method]; } });
const clean = node(utxos([[IN.transactionId, 1]]), mem());
const c = async (name, cfg, tx, hint, want) => { const g = await mk(cfg)(tx, hint); t(name + ' -> ' + g, g === want, 'got ' + g); };
(async () => {
  await c('clean, input unspent on both', { 'wss://n1': clean, 'wss://n2': clean }, TX, undefined, 'absent');
  await c('input spent on both', { 'wss://n1': node(utxos([]), mem()), 'wss://n2': node(utxos([]), mem()) }, TX, undefined, 'unknown');
  await c('one node lagging (input missing)', { 'wss://n1': clean, 'wss://n2': node(utxos([]), mem()) }, TX, undefined, 'unknown');
  await c('mempool sending non-empty', { 'wss://n1': node(utxos([[IN.transactionId, 1]]), mem([{ x: 1 }])), 'wss://n2': clean }, TX, undefined, 'unknown');
  await c('mempool receiving non-empty', { 'wss://n1': node(utxos([[IN.transactionId, 1]]), mem([], [{ x: 1 }])), 'wss://n2': clean }, TX, undefined, 'unknown');
  await c('node TIMEOUT text', { 'wss://n1': node('TIMEOUT', 'TIMEOUT'), 'wss://n2': clean }, TX, undefined, 'unknown');
  await c('node call throws', { 'wss://n1': new Error('boom'), 'wss://n2': clean }, TX, undefined, 'unknown');
  await c('one node malformed', { 'wss://n1': node('{"nope":1}', mem()), 'wss://n2': clean }, TX, undefined, 'unknown');
  const H = 'ff'.repeat(32);
  await c('hint txId among outputs -> mined', { 'wss://n1': node(utxos([[H, 1]]), mem()), 'wss://n2': node(utxos([]), mem()) }, TX, { txId: H }, 'mined');
  await c('hint txId mined even if input spent', { 'wss://n1': node(utxos([[H, 3]]), mem()), 'wss://n2': node(utxos([[H, 3]]), mem()) }, { inputs: [] }, { txId: H }, 'mined');
  await c('hint txId in mempool', { 'wss://n1': node(utxos([[IN.transactionId, 1]]), mem([{ txid: H }])), 'wss://n2': clean }, TX, { txId: H }, 'mempool');
  await c('hint not found, clean -> absent', { 'wss://n1': clean, 'wss://n2': clean }, TX, { txId: H }, 'absent');
  await c('no wallet-signed input', { 'wss://n1': clean, 'wss://n2': clean }, { inputs: [{ previousOutpoint: IN, signatureScript: '' }] }, undefined, 'unknown');
  await c('empty tx', { 'wss://n1': clean, 'wss://n2': clean }, {}, undefined, 'unknown');
  let th = false; try { createNodeLookup({ urls: [], address: A }); } catch (e) { th = true; } t('bad factory args throw', th);
  const OKR = { txId: 'ff'.repeat(32) };
  const mkNode = (subs, cfg) => { const n = { calls: 0, lookup: mk(cfg) }; n.submit = async () => { const s = subs[Math.min(n.calls++, subs.length - 1)]; if (s instanceof Error) throw s; return s; }; return n; };
  const r1 = await submitSafe({ node: mkNode([new Error('WRPC TIMEOUT'), OKR], { 'wss://n1': clean, 'wss://n2': clean }), rpcTx: TX, sleep: async () => {} });
  t('submitSafe + adapter: timeout, absent -> identical retry lands', r1.state === 'submitted', r1.state);
  const nd = mkNode([new Error('WRPC TIMEOUT')], { 'wss://n1': node(utxos([]), mem()), 'wss://n2': node(utxos([]), mem()) });
  const r2 = await submitSafe({ node: nd, rpcTx: TX, sleep: async () => {} });
  t('submitSafe + adapter: timeout, input spent -> ambiguous, one submit', r2.state === 'ambiguous' && nd.calls === 1, r2.state + ' calls ' + nd.calls);
  console.log(bad ? 'LOOKUP TESTS FAILED' : 'LOOKUP TESTS OK'); process.exit(bad);
})();
