'use strict';
const { engineKind } = require('./read.js');
let bad = 0;
const t = (name, ok, d) => { if (!ok) bad = 1; console.log((ok ? 'PASS ' : 'FAIL ') + name + (ok ? '' : ' | ' + d)); };
const vm = Uint8Array.from([0x52, 0x56, 0x4d, 0x01, 64, 0, 64, 0, 0]);
const js = Uint8Array.from(Buffer.from('\nfunction reliks(L, serial){ return 1; }'));
const c = (name, prog, lang, kind, cons) => { const r = engineKind(prog, lang); t(name, r.kind === kind && r.langConsistent === cons, JSON.stringify(r)); };
c('VM magic, lang 1', vm, 1, 'vm', true);
c('VM magic, lang 2', vm, 2, 'vm', true);
c('VM magic, lang 0 flagged', vm, 0, 'vm', false);
c('mainnet-style JS, lang 1', js, 1, 'js', true);
c('JS, lang 0', js, 0, 'js', true);
c('JS, lang 2 flagged', js, 2, 'js', false);
c('garbage is unknown', Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), 1, 'unknown', false);
c('empty is unknown', new Uint8Array(0), 1, 'unknown', false);
c('null is unknown', null, 1, 'unknown', false);
c('magic without header is unknown', Uint8Array.from([0x52, 0x56, 0x4d, 0x01]), 1, 'unknown', false);
c('Buffer input accepted', Buffer.from(vm), 2, 'vm', true);
c('lang as string', vm, '2', 'vm', true);
console.log(bad ? 'ENGINE TESTS FAILED' : 'ENGINE TESTS OK'); process.exit(bad);
