import WebSocket from 'ws';

// 1. Paste the exact transaction object generated by mint.ts here.
// Make sure it includes your computeBudget field!
const txPayload = {
    version: 1,
    inputs: [
        {
            previousOutpoint: {
                transactionId: "YOUR_TX_ID_HERE",
                index: 0
            },
            signatureScript: "YOUR_SIGNATURE_SCRIPT_HERE",
            sequence: 0,
            sigOpCount: 1, 
            computeBudget: 1000 // <- The field that was getting dropped!
        }
    ],
    outputs: [
        // ... your outputs here ...
    ],
    lockTime: 0,
    subnetworkId: "0000000000000000000000000000000000000000"
};

console.log("Connecting directly to Kaspa Testnet-10 Node...");

// 2. Connect directly to the node's wRPC interface (bypassing the REST server)
const ws = new WebSocket('ws://tn10-rpc.kaspa.org:16210');

ws.on('open', () => {
    console.log('✅ Connected to Node!');
    
    // 3. Wrap the transaction in the Kaspa wRPC JSON envelope
    const request = {
        id: 1,
        method: 'submitTransactionRequest',
        params: {
            transaction: txPayload,
            allowOrphan: false
        }
    };

    console.log('🚀 Broadcasting transaction...');
    ws.send(JSON.stringify(request));
});

ws.on('message', (data) => {
    console.log('\n📬 Node Response:');
    
    // Parse and print the node's response nicely
    try {
        const response = JSON.parse(data.toString());
        console.dir(response, { depth: null, colors: true });
        
        if (response.error) {
            console.error("❌ Broadcast Failed:", response.error.message);
        } else if (response.result && response.result.transactionId) {
            console.log("🎉 SUCCESS! Transaction ID:", response.result.transactionId);
        }
    } catch (e) {
        console.log(data.toString());
    }
    
    ws.close();
});

ws.on('error', (err) => {
    console.error('❌ WebSocket Error:', err.message);
});